### ISSUE TITLE
Nice job, don't run before you walk

### ISSUE THREAD

**Issue by dudeisbrendan03** [Expensiveee/prodige#1]
Congrats on your first major contributions to the OSS world, and welcome to the GitHub community- the following is targeted to this project but could be applied to your others.

Take this as advice and work off it, this isn't an attack:
- Your git repository looks unmaintained even though you just committed since you're committing in groups and not changes (you're not using git how you're supposed to, which also means you're losing a lot of file history)
- Your git commits need to be descriptive but also to the point, I recommend using <https://gitmoji.dev> to tag your issues with an emoji, then write a short (less than 50char) title that is blunt and to-the-point
- Your README is lacking and pretty much useless, beef it up with more information about the project.
A quick start, why it exists, who it's for, how to report issues
- Your GitHub community is not configured
Configure issues, PRs, community guidelines etc
- That NPM link is dead
- Use Ci/Cd (Actions or alternative e.g. Azure DevOps Pipelines) to test then publish to npm automagically
- Your documentation is *extremely* lacking and definitely not 'detailed', you're not describing how each function and class work, nor how to test and debug- you're just giving some examples
- Pick a side
You can't have `yarn` and `npm`, pick who you're going with.
I would recommend npm, but some people don't like the fact that they're an enterprise-managed OSS project, if you're against that, go yarn- if not npm.

I would highly recommend saying that this is a work in progress until you can sort out your repository and project.

I spotted you advertising this in a Discord, but you appeared to of left

**Comment by Expensiveee** [comment]
Hello @dudeisbrendan03 ,

First of all, **thank you** for the interest that you are giving to Prodige. I was surprised that someone took a bit of their time to take a look at my repository.

I read meticulously all the advice that you gave me, below, you can find  the improvements that I made or going to make:

- You were right, I'm not using git like I'm supposed to do,  so I took into consideration your advice and starting committing to changes.
- As you can see,  I started to use the emojis system to describe my commit.
- I updated my README to a cleaner and more readable version, it's still vague but,  I want people to read the [documentation](https://theexpensiveee.gitbook.io/prodige/).
- I have added templates for pull requests and issues.
- I have added a workflow that tests the code and publishes it to npm as soon as a new release is published. I still need to test the code when someone pushes using Github Actions. I'm working on it
- I'm planning to completely re-write the documentation in multiple languages.

I most certainly still have many improvements to make but as you said "don't run before you walk". I'm still learning how to walk as it's my first time 😉.

If you see that other improvements could be made, please open a new issue.

**Comment by dudeisbrendan03** [comment]
Welcome to GitHub, GLHF! :)
